<?php
define('_DB_SERVER_', 'wm66.wedos.net');
define('_DB_NAME_', 'd75717_solcos');
define('_DB_USER_', 'a75717_solcos');
define('_DB_PASSWD_', 'dUbFBfm6');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'JBVLYzsCIjHMmUXuO9ZDtX7U8yjm57UZKUDw1n9kbRU4FPvQAd4LMaaJ');
define('_COOKIE_IV_', 'gcnF6J8Y');
define('_PS_CREATION_DATE_', '2014-12-11');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', '0qjHLg4aavNMzJWAFnmTQNa4SEGh9FqB');
define('_RIJNDAEL_IV_', 'CgB2NmHECw1xQRY1YwBTTA==');
